# === Application ===
spring.application.name=shortly
server.port=9876

# === Application Properties ===
app.base-url=http://localhost:9876
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=1800000

# === DB Connection ===
spring.datasource.url=jdbc:mysql://localhost:3306/shortly?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Logging ===
logging.file.name=logs/shortly.log